services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:inception42
    # env_file:
    #   - .env
    ports:
      - "8037:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - mynet
    restart: always

  websrv:
    container_name: webserv
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: webserv:inception42
    # ports:
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge
